INSERT INTO communes (id,label,tag,short,province_id) VALUES
	 (1,'Arica','arica','Arica',1),
	 (2,'Camarones','camarones','Camarones',1),
	 (3,'General Lagos','gral_lagos','Gral. Lagos',2),
	 (4,'Putre','putre','Putre',2),
	 (5,'Alto Hospicio','alto_hospicio','A. Hospicio',3),
	 (6,'Iquique','iquique','Iquique',3),
	 (7,'Camiña','camina','Camiña',4),
	 (8,'Colchane','colchane','Colchane',4),
	 (9,'Huara','huara','Huara',4),
	 (10,'Pica','pica','Pica',4),
	 (11,'Pozo Almonte','pozo_almonte','P. Almonte',4),
	 (12,'Antofagasta','antofagasta','Antofagasta',5),
	 (13,'Mejillones','mejillones','Mejillones',5),
	 (14,'Sierra Gorda','sierra_gorda','S. Gorda',5),
	 (15,'Taltal','taltal','Taltal',5),
	 (16,'Calama','calama','Calama',6),
	 (17,'Ollague','ollague','Ollague',6),
	 (18,'San Pedro de Atacama','san_pedro_de_atacama','San Pedro Atacama',6),
	 (19,'María Elena','maria_elena','María Elena',7),
	 (20,'Tocopilla','tocopilla','Tocopilla',7),
	 (21,'Chañaral','chanaral','Chañaral',8),
	 (22,'Diego de Almagro','diego_de_almagro','Diego de Almagro',8),
	 (23,'Caldera','caldera','Caldera',9),
	 (24,'Copiapó','copiapo','Copiapó',9),
	 (25,'Tierra Amarilla','tierra_amarilla','Tierra Amarilla',9),
	 (26,'Alto del Carmen','alto_del_carmen','A. del Carmen',10),
	 (27,'Freirina','freirina','Freirina',10),
	 (28,'Huasco','huasco','Huasco',10),
	 (29,'Vallenar','vallenar','Vallenar',10),
	 (30,'Canela','canela','Canela',11),
	 (31,'Illapel','illapel','Illapel',11),
	 (32,'Los Vilos','los_vilos','Los Vilos',11),
	 (33,'Salamanca','salamanca','Salamanca',11),
	 (34,'Andacollo','andacollo','Andacollo',12),
	 (35,'Coquimbo','coquimbo','Coquimbo',12),
	 (36,'La Higuera','la_higuera','La Higuera',12),
	 (37,'La Serena','la_serena','La Serena',12),
	 (38,'Paihuano','paihuano','Paihuano',12),
	 (39,'Vicuña','vicuna','Vicuña',12),
	 (40,'Combarbalá','combarbala','Combarbalá',13),
	 (41,'Monte Patria','monte_patria','Monte Patria',13),
	 (42,'Ovalle','ovalle','Ovalle',13),
	 (43,'Punitaqui','punitaqui','Punitaqui',13),
	 (44,'Río Hurtado','rio_hurtado','Río Hurtado',13),
	 (45,'Isla de Pascua','isla_de_pascua','Isla de Pascua',14),
	 (46,'Calle Larga','calle_larga','Calle Larga',15),
	 (47,'Los Andes','los_andes','Los Andes',15),
	 (48,'Rinconada','rinconada','Rinconada',15),
	 (49,'San Esteban','san_esteban','San Esteban',15),
	 (50,'La Ligua','la_ligua','La Ligua',16),
	 (51,'Papudo','papudo','Papudo',16),
	 (52,'Petorca','petorca','Petorca',16),
	 (53,'Zapallar','zapallar','Zapallar',16),
	 (54,'Hijuelas','hijuelas','Hijuelas',17),
	 (55,'La Calera','la_calera','La Calera',17),
	 (56,'La Cruz','la_cruz','La Cruz',17),
	 (57,'Limache','limache','Limache',54),
	 (58,'Nogales','nogales','Nogales',17),
	 (59,'Olmué','olmue','Olmué',54),
	 (60,'Quillota','quillota','Quillota',17),
	 (61,'Algarrobo','algarrobo','Algarrobo',18),
	 (62,'Cartagena','cartagena','Cartagena',18),
	 (63,'El Quisco','el_quisco','El Quisco',18),
	 (64,'El Tabo','el_tabo','El Tabo',18),
	 (65,'San Antonio','san_antonio','San Antonio',18),
	 (66,'Santo Domingo','santo_domingo','Sto. Domingo',18),
	 (67,'Catemu','catemu','Catemu',19),
	 (68,'Llaillay','llaillay','Llaillay',19),
	 (69,'Panquehue','panquehue','Panquehue',19),
	 (70,'Putaendo','putaendo','Putaendo',19),
	 (71,'San Felipe','san_felipe','San Felipe',19),
	 (72,'Santa María','santa_maria','Santa María',19),
	 (73,'Casablanca','casablanca','Casablanca',20),
	 (74,'Concón','concon','Concón',20),
	 (75,'Juan Fernández','juan_fernandez','J. Fernández',20),
	 (76,'Puchuncaví','puchuncavi','Puchuncaví',20),
	 (77,'Quilpué','quilpue','Quilpué',54),
	 (78,'Quintero','quintero','Quintero',20),
	 (79,'Valparaíso','valparaiso','Valparaíso',20),
	 (80,'Villa Alemana','villa_alemana','Villa Alemana',54),
	 (81,'Viña del Mar','vina_del_mar','Viña del Mar',20),
	 (82,'Colina','colina','Colina',21),
	 (83,'Lampa','lampa','Lampa',21),
	 (84,'Tiltil','tiltil','Tiltil',21),
	 (85,'Pirque','pirque','Pirque',22),
	 (86,'Puente Alto','puente_alto','Puente Alto',22),
	 (87,'San José de Maipo','san_jose_de_maipo','San José de Maipo',22),
	 (88,'Buin','buin','Buin',23),
	 (89,'Calera de Tango','calera_de_tango','Calera de Tango',23),
	 (90,'Paine','paine','Paine',23),
	 (91,'San Bernardo','san_bernardo','San Bernardo',23),
	 (92,'Alhué','alhue','Alhué',24),
	 (93,'Curacaví','curacavi','Curacaví',24),
	 (94,'María Pinto','maria_pinto','María Pinto',24),
	 (95,'Melipilla','melipilla','Melipilla',24),
	 (96,'San Pedro','san_pedro','San Pedro',24),
	 (97,'Cerrillos','cerrillos','Cerrillos',25),
	 (98,'Cerro Navia','cerro_navia','Cerro Navia',25),
	 (99,'Conchalí','conchali','Conchalí',25),
	 (100,'El Bosque','el_bosque','El Bosque',25),
	 (101,'Estación Central','estacion_central','E. Central',25),
	 (102,'Huechuraba','huechuraba','Huechuraba',25),
	 (103,'Independencia','independencia','Independencia',25),
	 (104,'La Cisterna','la_cisterna','La Cisterna',25),
	 (105,'La Granja','la_granja','La Granja',25),
	 (106,'La Florida','la_florida','La Florida',25),
	 (107,'La Pintana','la_pintana','La Pintana',25),
	 (108,'La Reina','la_reina','La Reina',25),
	 (109,'Las Condes','las_condes','Las Condes',25),
	 (110,'Lo Barnechea','lo_barnechea','Lo Barnechea',25),
	 (111,'Lo Espejo','lo_espejo','Lo Espejo',25),
	 (112,'Lo Prado','lo_prado','Lo Prado',25),
	 (113,'Macul','macul','Macul',25),
	 (114,'Maipú','maipu','Maipú',25),
	 (115,'Ñuñoa','nunoa','Ñuñoa',25),
	 (116,'Pedro Aguirre Cerda','pedro_aguirre_cerda','P. Aguirre Cerda',25),
	 (117,'Peñalolén','penalolen','Peñalolén',25),
	 (118,'Providencia','providencia','Providencia',25),
	 (119,'Pudahuel','pudahuel','Pudahuel',25),
	 (120,'Quilicura','quilicura','Quilicura',25),
	 (121,'Quinta Normal','quinta_normal','Quinta Normal',25),
	 (122,'Recoleta','recoleta','Recoleta',25),
	 (123,'Renca','renca','Renca',25),
	 (124,'San Miguel','san_miguel','San Miguel',25),
	 (125,'San Joaquín','san_joaquin','San Joaquín',25),
	 (126,'San Ramón','san_ramon','San Ramón',25),
	 (127,'Santiago','santiago','Santiago',25),
	 (128,'Vitacura','vitacura','Vitacura',25),
	 (129,'El Monte','el_monte','El Monte',26),
	 (130,'Isla de Maipo','isla_de_maipo','I. de Maipo',26),
	 (131,'Padre Hurtado','padre_hurtado','Padre Hurtado',26),
	 (132,'Peñaflor','penaflor','Peñaflor',26),
	 (133,'Talagante','talagante','Talagante',26),
	 (134,'Codegua','codegua','Codegua',27),
	 (135,'Coínco','coinco','Coínco',27),
	 (136,'Coltauco','coltauco','Coltauco',27),
	 (137,'Doñihue','donihue','Doñihue',27),
	 (138,'Graneros','graneros','Graneros',27),
	 (139,'Las Cabras','las_cabras','Las Cabras',27),
	 (140,'Machalí','machali','Machalí',27),
	 (141,'Malloa','malloa','Malloa',27),
	 (142,'Mostazal','mostazal','Mostazal',27),
	 (143,'Olivar','olivar','Olivar',27),
	 (144,'Peumo','peumo','Peumo',27),
	 (145,'Pichidegua','pichidegua','Pichidegua',27),
	 (146,'Quinta de Tilcoco','quinta_de_tilcoco','Qta. de Tilcoco',27),
	 (147,'Rancagua','rancagua','Rancagua',27),
	 (148,'Rengo','rengo','Rengo',27),
	 (149,'Requínoa','requinoa','Requínoa',27),
	 (150,'San Vicente de Tagua Tagua','san_vicente_de_tagua_tagua','San Vicente',27),
	 (151,'La Estrella','la_estrella','La Estrella',28),
	 (152,'Litueche','litueche','Litueche',28),
	 (153,'Marchihue','marchihue','Marchihue',28),
	 (154,'Navidad','navidad','Navidad',28),
	 (155,'Paredones','paredones','Paredones',28),
	 (156,'Pichilemu','pichilemu','Pichilemu',28),
	 (157,'Chépica','chepica','Chépica',29),
	 (158,'Chimbarongo','chimbarongo','Chimbarongo',29),
	 (159,'Lolol','lolol','Lolol',29),
	 (160,'Nancagua','nancagua','Nancagua',29),
	 (161,'Palmilla','palmilla','Palmilla',29),
	 (162,'Peralillo','peralillo','Peralillo',29),
	 (163,'Placilla','placilla','Placilla',29),
	 (164,'Pumanque','pumanque','Pumanque',29),
	 (165,'San Fernando','san_fernando','San Fernando',29),
	 (166,'Santa Cruz','santa_cruz','Santa Cruz',29),
	 (167,'Cauquenes','cauquenes','Cauquenes',30),
	 (168,'Chanco','chanco','Chanco',30),
	 (169,'Pelluhue','pelluhue','Pelluhue',30),
	 (170,'Curicó','curico','Curicó',31),
	 (171,'Hualañé','hualane','Hualañé',31),
	 (172,'Licantén','licanten','Licantén',31),
	 (173,'Molina','molina','Molina',31),
	 (174,'Rauco','rauco','Rauco',31),
	 (175,'Romeral','romeral','Romeral',31),
	 (176,'Sagrada Familia','sagrada_familia','Sagrada Familia',31),
	 (177,'Teno','teno','Teno',31),
	 (178,'Vichuquén','vichuquen','Vichuquén',31),
	 (179,'Colbún','colbun','Colbún',32),
	 (180,'Linares','linares','Linares',32),
	 (181,'Longaví','longavi','Longaví',32),
	 (182,'Parral','parral','Parral',32),
	 (183,'Retiro','retiro','Retiro',32),
	 (184,'San Javier','san_javier','San Javier',32),
	 (185,'Villa Alegre','villa_alegre','Villa Alegre',32),
	 (186,'Yerbas Buenas','yerbas_buenas','Yerbas Buenas',32),
	 (187,'Constitución','constitucion','Constitución',33),
	 (188,'Curepto','curepto','Curepto',33),
	 (189,'Empedrado','empedrado','Empedrado',33),
	 (190,'Maule','maule','Maule',33),
	 (191,'Pelarco','pelarco','Pelarco',33),
	 (192,'Pencahue','pencahue','Pencahue',33),
	 (193,'Río Claro','rio_claro','Río Claro',33),
	 (194,'San Clemente','san_clemente','San Clemente',33),
	 (195,'San Rafael','san_rafael','San Rafael',33),
	 (196,'Talca','talca','Talca',33),
	 (197,'Arauco','arauco','Arauco',34),
	 (198,'Cañete','canete','Cañete',34),
	 (199,'Contulmo','contulmo','Contulmo',34),
	 (200,'Curanilahue','curanilahue','Curanilahue',34),
	 (201,'Lebu','lebu','Lebu',34),
	 (202,'Los Álamos','los_alamos','Los Álamos',34),
	 (203,'Tirúa','tirua','Tirúa',34),
	 (204,'Alto Biobío','alto_biobio','Alto Biobío',35),
	 (205,'Antuco','antuco','Antuco',35),
	 (206,'Cabrero','cabrero','Cabrero',35),
	 (207,'Laja','laja','Laja',35),
	 (208,'Los Ángeles','los_angeles','Los Ángeles',35),
	 (209,'Mulchén','mulchen','Mulchén',35),
	 (210,'Nacimiento','nacimiento','Nacimiento',35),
	 (211,'Negrete','negrete','Negrete',35),
	 (212,'Quilaco','quilaco','Quilaco',35),
	 (213,'Quilleco','quilleco','Quilleco',35),
	 (214,'San Rosendo','san_rosendo','San Rosendo',35),
	 (215,'Santa Bárbara','santa_barbara','Santa Bárbara',35),
	 (216,'Tucapel','tucapel','Tucapel',35),
	 (217,'Yumbel','yumbel','Yumbel',35),
	 (218,'Chiguayante','chiguayante','Chiguayante',36),
	 (219,'Concepción','concepcion','Concepción',36),
	 (220,'Coronel','coronel','Coronel',36),
	 (221,'Florida','florida','Florida',36),
	 (222,'Hualpén','hualpen','Hualpén',36),
	 (223,'Hualqui','hualqui','Hualqui',36),
	 (224,'Lota','lota','Lota',36),
	 (225,'Penco','penco','Penco',36),
	 (226,'San Pedro de La Paz','san_pedro_de_la_paz','S. Pedro de La Paz',36),
	 (227,'Santa Juana','santa_juana','Sta. Juana',36),
	 (228,'Talcahuano','talcahuano','Talcahuano',36),
	 (229,'Tomé','tome','Tomé',36),
	 (230,'Bulnes','bulnes','Bulnes',55),
	 (231,'Chillán','chillan','Chillán',55),
	 (232,'Chillán Viejo','chillan_viejo','Chillán Viejo',55),
	 (233,'Cobquecura','cobquecura','Cobquecura',37),
	 (234,'Coelemu','coelemu','Coelemu',37),
	 (235,'Coihueco','coihueco','Coihueco',56),
	 (236,'El Carmen','el_carmen','El Carmen',55),
	 (237,'Ninhue','ninhue','Ninhue',37),
	 (238,'Ñiquen','niquen','Ñiquen',56),
	 (239,'Pemuco','pemuco','Pemuco',55),
	 (240,'Pinto','pinto','Pinto',55),
	 (241,'Portezuelo','portezuelo','Portezuelo',37),
	 (242,'Quillón','quillon','Quillón',55),
	 (243,'Quirihue','quirihue','Quirihue',37),
	 (244,'Ránquil','ranquil','Ránquil',37),
	 (245,'San Carlos','san_carlos','San Carlos',56),
	 (246,'San Fabián','san_fabian','San Fabián',56),
	 (247,'San Ignacio','san_ignacio','San Ignacio',55),
	 (248,'San Nicolás','san_nicolas','San Nicolás',56),
	 (249,'Treguaco','treguaco','Treguaco',37),
	 (250,'Yungay','yungay','Yungay',55),
	 (251,'Carahue','carahue','Carahue',38),
	 (252,'Cholchol','cholchol','Cholchol',38),
	 (253,'Cunco','cunco','Cunco',38),
	 (254,'Curarrehue','curarrehue','Curarrehue',38),
	 (255,'Freire','freire','Freire',38),
	 (256,'Galvarino','galvarino','Galvarino',38),
	 (257,'Gorbea','gorbea','Gorbea',38),
	 (258,'Lautaro','lautaro','Lautaro',38),
	 (259,'Loncoche','loncoche','Loncoche',38),
	 (260,'Melipeuco','melipeuco','Melipeuco',38),
	 (261,'Nueva Imperial','nueva_imperial','Nva. Imperial',38),
	 (262,'Padre Las Casas','padre_las_casas','P. Las Casas',38),
	 (263,'Perquenco','perquenco','Perquenco',38),
	 (264,'Pitrufquén','pitrufquen','Pitrufquén',38),
	 (265,'Pucón','pucon','Pucón',38),
	 (266,'Puerto Saavedra','puerto_saavedra','Pto. Saavedra',38),
	 (267,'Temuco','temuco','Temuco',38),
	 (268,'Teodoro Schmidt','teodoro_schmidt','Teodoro Schmidt',38),
	 (269,'Toltén','tolten','Toltén',38),
	 (270,'Vilcún','vilcun','Vilcún',38),
	 (271,'Villarrica','villarrica','Villarrica',38),
	 (272,'Angol','angol','Angol',39),
	 (273,'Collipulli','collipulli','Collipulli',39),
	 (274,'Curacautín','curacautin','Curacautín',39),
	 (275,'Ercilla','ercilla','Ercilla',39),
	 (276,'Lonquimay','lonquimay','Lonquimay',39),
	 (277,'Los Sauces','los_sauces','Los Sauces',39),
	 (278,'Lumaco','lumaco','Lumaco',39),
	 (279,'Purén','puren','Purén',39),
	 (280,'Renaico','renaico','Renaico',39),
	 (281,'Traiguén','traiguen','Traiguén',39),
	 (282,'Victoria','victoria','Victoria',39),
	 (283,'Corral','corral','Corral',40),
	 (284,'Lanco','lanco','Lanco',40),
	 (285,'Los Lagos','los_lagos','Los Lagos',40),
	 (286,'Máfil','mafil','Máfil',40),
	 (287,'Mariquina','mariquina','Mariquina',40),
	 (288,'Paillaco','paillaco','Paillaco',40),
	 (289,'Panguipulli','panguipulli','Panguipulli',40),
	 (290,'Valdivia','valdivia','Valdivia',40),
	 (291,'Futrono','futrono','Futrono',41),
	 (292,'La Unión','la_union','La Unión',41),
	 (293,'Lago Ranco','lago_ranco','Lago Ranco',41),
	 (294,'Río Bueno','rio_bueno','Río Bueno',41),
	 (295,'Ancud','ancud','Ancud',42),
	 (296,'Castro','castro','Castro',42),
	 (297,'Chonchi','chonchi','Chonchi',42),
	 (298,'Curaco de Vélez','curaco_de_velez','C. de Vélez',42),
	 (299,'Dalcahue','dalcahue','Dalcahue',42),
	 (300,'Puqueldón','puqueldon','Puqueldón',42),
	 (301,'Queilén','queilen','Queilén',42),
	 (302,'Quemchi','quemchi','Quemchi',42),
	 (303,'Quellón','quellon','Quellón',42),
	 (304,'Quinchao','quinchao','Quinchao',42),
	 (305,'Calbuco','calbuco','Calbuco',43),
	 (306,'Cochamó','cochamo','Cochamó',43),
	 (307,'Fresia','fresia','Fresia',43),
	 (308,'Frutillar','frutillar','Frutillar',43),
	 (309,'Llanquihue','llanquihue','Llanquihue',43),
	 (310,'Los Muermos','los_muermos','Los Muermos',43),
	 (311,'Maullín','maullin','Maullín',43),
	 (312,'Puerto Montt','puerto_montt','Pto. Montt',43),
	 (313,'Puerto Varas','puerto_varas','Pto. Varas',43),
	 (314,'Osorno','osorno','Osorno',44),
	 (315,'Puerto Octay','puerto_octay','Pto. Octay',44),
	 (316,'Purranque','purranque','Purranque',44),
	 (317,'Puyehue','puyehue','Puyehue',44),
	 (318,'Río Negro','rio_negro','Río Negro',44),
	 (319,'San Juan de la Costa','san_juan_de_la_costa','San Juan de la Costa',44),
	 (320,'San Pablo','san_pablo','San Pablo',44),
	 (321,'Chaitén','chaiten','Chaitén',45),
	 (322,'Futaleufú','futaleufu','Futaleufú',45),
	 (323,'Hualaihué','hualaihue','Hualaihué',45),
	 (324,'Palena','palena','Palena',45),
	 (325,'Aysén','aysen','Aysén',46),
	 (326,'Cisnes','cisnes','Cisnes',46),
	 (327,'Guaitecas','guaitecas','Guaitecas',46),
	 (328,'Cochrane','cochrane','Cochrane',47),
	 (329,'O''higgins','ohiggins','O''higgins',47),
	 (330,'Tortel','tortel','Tortel',47),
	 (331,'Coyhaique','coyhaique','Coyhaique',48),
	 (332,'Lago Verde','lago_verde','Lago Verde',48),
	 (333,'Chile Chico','chile_chico','Chile Chico',49),
	 (334,'Río Ibáñez','rio_ibanez','Río Ibáñez',49),
	 (335,'Antártica','antartica','Antártica',50),
	 (336,'Cabo de Hornos','cabo_de_hornos','C. de Hornos',50),
	 (337,'Laguna Blanca','laguna_blanca','Laguna Blanca',51),
	 (338,'Punta Arenas','punta_arenas','Punta Arenas',51),
	 (339,'Río Verde','rio_verde','Río Verde',51),
	 (340,'San Gregorio','san_gregorio','San Gregorio',51),
	 (341,'Porvenir','porvenir','Porvenir',52),
	 (342,'Primavera','primavera','Primavera',52),
	 (343,'Timaukel','timaukel','Timaukel',52),
	 (344,'Natales','natales','Natales',53),
	 (345,'Torres del Paine','torres_del_paine','T. del Paine',53),
	 (346,'Cabildo','cabildo','Cabildo',16);
