INSERT INTO provinces (id,label,tag,short,region_id) VALUES
	 (1,'Arica','arica','Arica',1),
	 (2,'Parinacota','parinacota','Parinacota',1),
	 (3,'Iquique','iquique','Iquique',2),
	 (4,'El Tamarugal','tamarugal','Tamarugal',2),
	 (5,'Antofagasta','antofagasta','Antofagasta',3),
	 (6,'El Loa','loa','Loa',3),
	 (7,'Tocopilla','tocopilla','Tocopilla',3),
	 (8,'Chañaral','chanaral','Chañaral',4),
	 (9,'Copiapó','copiapo','Copiapó',4),
	 (10,'Huasco','huasco','Huasco',4),
	 (11,'Choapa','choapa','Choapa',5),
	 (12,'Elqui','elqui','Elqui',5),
	 (13,'Limarí','limari','Limarí',5),
	 (14,'Isla de Pascua','isla_pascua','Pascua',6),
	 (15,'Los Andes','andes','Andes',6),
	 (16,'Petorca','petorca','Petorca',6),
	 (17,'Quillota','quillota','Quillota',6),
	 (18,'San Antonio','san_antonio','San Antonio',6),
	 (19,'San Felipe de Aconcagua','san_felipe','San Felipe',6),
	 (20,'Valparaiso','valparaiso','Valparaiso',6),
	 (21,'Chacabuco','chacabuco','Chacabuco',7),
	 (22,'Cordillera','cordillera','Cordillera',7),
	 (23,'Maipo','maipo','Maipo',7),
	 (24,'Melipilla','melipilla','Melipilla',7),
	 (25,'Santiago','santiago','Santiago',7),
	 (26,'Talagante','talagante','Talagante',7),
	 (27,'Cachapoal','cachapoal','Cachapoal',8),
	 (28,'Cardenal Caro','cardenal_caro','Cardenal Caro',8),
	 (29,'Colchagua','colchagua','Colchagua',8),
	 (30,'Cauquenes','cauquenes','Cauquenes',9),
	 (31,'Curicó','curico','Curicó',9),
	 (32,'Linares','linares','Linares',9),
	 (33,'Talca','talca','Talca',9),
	 (34,'Arauco','arauco','Arauco',10),
	 (35,'Bio Bío','biobio','Bio Bío',10),
	 (36,'Concepción','concepcion','Concepción',10),
	 (37,'Itata','itata','Itata',16),
	 (38,'Cautín','cautin','Cautín',11),
	 (39,'Malleco','malleco','Malleco',11),
	 (40,'Valdivia','valdivia','Valdivia',12),
	 (41,'Ranco','ranco','Ranco',12),
	 (42,'Chiloé','chiloe','Chiloé',13),
	 (43,'Llanquihue','llanquihue','Llanquihue',13),
	 (44,'Osorno','osorno','Osorno',13),
	 (45,'Palena','palena','Palena',13),
	 (46,'Aysén','aysen','Aysén',14),
	 (47,'Capitán Prat','capitan_prat','Prat',14),
	 (48,'Coyhaique','coyhaique','Coyhaique',14),
	 (49,'General Carrera','general_carrera','Carrera',14),
	 (50,'Antártica Chilena','antartica','Antártica',15),
	 (51,'Magallanes','magallanes','Magallanes',15),
	 (52,'Tierra del Fuego','tierra_fuego','Tierra del Fuego',15),
	 (53,'Última Esperanza','ultima_esperanza','Última Esperanza',15),
	 (54,'Marga Marga','marga_marga','Marga Marga',6),
	 (55,'Diguillín','diguillin','Diguillín',16),
	 (56,'Punilla','punilla','Punilla',16);